name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: chmod +x ./Main.java
      - run: ./Main.java
    - name: GitHub Push
        # You may pin to the exact commit or the version.
        # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Use the GitHub token provided by secrets
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Destination branch to push changes, default is master
          branch: ${{ github.ref }}
          # Force push changes
          force: true
          # Directory to change to before pushing. Specify as current directory
          directory: "."
